server:
  port: 9090

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:

      default-filters:
        - name: AddAuthUserIdHeaderFilter
      routes:
        - id: auth-service
          uri: http://localhost:9191
          predicates:
            - Path=/api/auth/**
        - id: customer-service
          uri: http://localhost:9194
          predicates:
            - Path=/api/customers/**
        - id: business-service
          uri: http://localhost:9195
          predicates:
            - Path=/api/businesses/**,/api/business-owners/**
        - id: appointment-service
          uri: http://localhost:9197
          predicates:
            - Path=/api/appointments/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            - "http://localhost:3000"
            - "http://127.0.0.1:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*" # Bütün başlıqlara icazə ver
            allowCredentials: true # Cookie və auth header-ləri kimi credential-ları ötürməyə icazə ver
            maxAge: 3600 # Pre-flight (OPTIONS) sorğularının keşlənmə müddəti


jwt:
  secret: q0+DTRJNAJzq8FXZHweVp8RUAEDCrEFwn7IuVyb8If70sZzmmTlRs+UE/zeq3kJzMRIrkVXtRuC14vXNAr8xfQ==
  expiration:
    ms: 300000
